export enum DomainEvent {
    SUBSCRIPTION_CREATED = "SUBSCRIPTION_CREATED",
    SUBSCRIPTION_UPDATED = "SUBSCRIPTION_UPDATED",
    SUBSCRIPTION_CANCELED = "SUBSCRIPTION_CANCELED",
    SUBSCRIPTION_CHANGED = "SUBSCRIPTION_CHANGED",
  
    BILLING_SNAPSHOT_CREATED = "BILLING_SNAPSHOT_CREATED",
  
    INVOICE_CREATED = "INVOICE_CREATED",
    INVOICE_PAID = "INVOICE_PAID",
    INVOICE_OVERDUE = "INVOICE_OVERDUE",
}